//! The class file

const std = @import("std");
const mem = std.mem;
const native_endian = @import("builtin").target.cpu.arch.endian();

// magic: u32,
minor_version: u16,
major_version: u16,
// constant_pool_count: u16,
constant_pool: ConstantPool,
access_flags: ClassAccessFlags,
this_class: u16,
super_class: u16,
// interfaces_count: u16,
interfaces: Interfaces,
// fields_count: u16,
fields: Fields,
// methods_count: u16,
methods: Methods,
// attributes_count: u16,
attributes: Attributes,

const ClassFile = @This();

// NOTE(anas): if we store them as slices it will be more efficient (probably), but we'll need to do alot of add, remove operations
pub const Interfaces = std.ArrayList(u16);
pub const Fields = std.ArrayList(FieldInfo);
pub const Methods = std.ArrayList(MethodInfo);
pub const Attributes = std.ArrayList(AttributeInfo);

pub const MAGIC: u32 = 0xCAFEBABE;

// Access flags.
pub const ACC_PUBLIC: u16 = 0x0001; // Declared public; may be accessed from outside its package.
pub const ACC_PRIVATE: u16 = 0x0002; // Declared private; accessible only within the defining class and other classes belonging to the same nest (§5.4.4).
pub const ACC_PROTECTED: u16 = 0x0004; // Declared protected; may be accessed within subclasses.
pub const ACC_STATIC: u16 = 0x0008; // Declared static.
pub const ACC_FINAL: u16 = 0x0010; // Declared final; no subclasses allowed.
pub const ACC_SUPER: u16 = 0x0020; // Treat superclass methods specially when invoked by the invokespecial instruction.
pub const ACC_SYNCHRONIZED: u16 = 0x0020; // Declared synchronized; invocation is wrapped by a monitor use.
pub const ACC_VOLATILE: u16 = 0x0040; // Declared volatile; cannot be cached.
pub const ACC_BRIDGE: u16 = 0x0040; // A bridge method, generated by the compiler.
pub const ACC_TRANSIENT: u16 = 0x0080; // Declared transient; not written or read by a persistent object manager.
pub const ACC_VARARGS: u16 = 0x0080; // Declared with variable number of arguments.
pub const ACC_NATIVE: u16 = 0x0100; // Declared native; implemented in a language other than the Java programming language.
pub const ACC_INTERFACE: u16 = 0x0200; // Is an interface, not a class.
pub const ACC_ABSTRACT: u16 = 0x0400; // Declared abstract; must not be instantiated.
pub const ACC_STRICT: u16 = 0x0800; // In a class file whose major version number is at least 46 and at most 60: Declared strictfp.
pub const ACC_SYNTHETIC: u16 = 0x1000; // Declared synthetic; not present in the source code.
pub const ACC_ANNOTATION: u16 = 0x2000; // Declared as an annotation interface.
pub const ACC_ENUM: u16 = 0x4000; // Declared as an enum class.
pub const ACC_MODULE: u16 = 0x8000; // Is a module, not a class or interface.

/// The class file parser
pub const Reader = struct {
    bytes: []const u8,
    cursor: usize = 0,
    allocator: mem.Allocator,

    pub inline fn init(allocator: mem.Allocator, bytes: []const u8) Reader {
        return .{
            .bytes = bytes,
            .allocator = allocator,
        };
    }

    inline fn _read_int(this: *Reader, comptime V: type) V {
        // NOTE(anas): all multi-byte values are encoded as big-endian.
        return mem.bigToNative(V, mem.bytesToValue(V, this.bytes[this.cursor..(blk: {
            this.cursor += @sizeOf(V);
            break :blk this.cursor;
        })]));
    }

    fn read_u32(this: *Reader) u32 {
        return this._read_int(u32);
    }

    fn read_u16(this: *Reader) u16 {
        return this._read_int(u16);
    }

    fn read_u8(this: *Reader) u8 {
        const n = this.bytes[this.cursor];
        this.cursor += 1;
        return n;
    }

    inline fn expect_n_bytes(this: *const Reader, n: usize) !void {
        if (this.bytes.len - this.cursor < n) return error.NoEnughBytes;
    }

    inline fn _have_int(this: *const Reader, comptime V: type) bool {
        const s = @sizeOf(V);
        return (this.bytes.len - this.cursor) >= s;
    }

    fn have_u32(this: *const Reader) bool {
        return this._have_int(u32);
    }

    fn have_u16(this: *const Reader) bool {
        return this._have_int(u16);
    }

    fn have_u8(this: *const Reader) bool {
        return this._have_int(u8);
    }

    inline fn _try_read_int(this: *Reader, comptime V: type) !V {
        if (!this._have_int(V)) return error.UnExpectedEOF;
        // NOTE(anas): all multi-byte values are encoded as big-endian.
        return mem.bigToNative(V, mem.bytesToValue(V, this.bytes[this.cursor..(blk: {
            this.cursor += @sizeOf(V);
            break :blk this.cursor;
        })]));
    }

    fn checked_read_u32(this: *Reader) !u32 {
        return try this._try_read_int(u32);
    }

    fn checked_read_u16(this: *Reader) !u16 {
        return try this._try_read_int(u16);
    }

    fn checked_read_u8(this: *Reader) !u8 {
        return try this._try_read_int(u8);
    }

    inline fn fill_buff(this: *Reader, buf: []u8) !void {
        try this.expect_n_bytes(buf.len);
        @memcpy(buf, this.bytes[this.cursor..blk: {
            this.cursor += buf.len;
            break :blk this.cursor;
        }]);
    }

    pub fn read_struct(this: *Reader, comptime T: type) !T {
        // Only extern and packed structs have defined in-memory layout.
        comptime std.debug.assert(@typeInfo(T).@"struct".layout != .auto);
        var res: [1]T = undefined;
        try this.fill_buff(mem.sliceAsBytes(res[0..]));
        if (native_endian != .big) {
            mem.byteSwapAllFields(T, &res[0]);
        }
        return res[0];
    }

    /// Check if the inner bytes might represent a _somewhat_ valid class file.
    /// You have to call this before `read_class` or do the initial length check on your side.
    pub inline fn is_somewhat_valid(this: *Reader) bool {
        // Check if it at least have the first 4 members
        if (this.bytes.len < 10) return false;
        const magic = this.read_u32();
        if (magic != MAGIC) return false;
        return true;
    }

    pub fn read_class(this: *Reader) !ClassFile {
        // WARNING(anas): here we assume that the user has already checked that the inner bytes array has at least 10 bytes - 4 for the magic
        const minor_version = this.read_u16();
        const major_version = this.read_u16();

        const constant_pool_count: u16 = this.read_u16();
        var constant_pool = try ConstantPool.initCapacity(this.allocator, constant_pool_count);
        errdefer constant_pool.deinit();
        {
            var i: usize = 0;
            while (i < constant_pool_count - 1) {
                // const c = try ConstantInfo.read(reader, this.allocator);
                const c = try this.read_constant_info();
                // NOTE(anas): apparently the `constant_pool_count` counts the 8-bytes values as a two separate items.
                // This done to keep the size of our `ConstantInfo` union 32bit
                if (c == .long or c == .double) {
                    constant_pool.appendAssumeCapacity(c);
                    // read the second half of the big number
                    const low_bytes: u32 = try this.checked_read_u32();
                    if (c == .long) {
                        constant_pool.appendAssumeCapacity(.{ .long = .{ .low_bytes = low_bytes } });
                    } else {
                        constant_pool.appendAssumeCapacity(.{ .double = .{ .low_bytes = low_bytes } });
                    }
                    i += 2;
                    continue;
                }
                constant_pool.appendAssumeCapacity(c);
                i += 1;
            }
        }

        try this.expect_n_bytes(@sizeOf(u16) * 4);
        const access_flags: ClassAccessFlags = @bitCast(this.read_u16());
        const this_class = this.read_u16();
        const super_class = this.read_u16();
        const interfaces_count: u16 = this.read_u16();
        try this.expect_n_bytes(@sizeOf(u16) * interfaces_count);
        var interfaces = try Interfaces.initCapacity(this.allocator, interfaces_count);
        errdefer interfaces.deinit();
        for (0..interfaces_count) |_| {
            interfaces.appendAssumeCapacity(this.read_u16());
        }

        const fields_count: u16 = try this.checked_read_u16();
        var fields = try Fields.initCapacity(this.allocator, fields_count);
        errdefer fields.deinit();
        for (0..fields_count) |_| {
            fields.appendAssumeCapacity(try this.read_field_info(&constant_pool));
        }

        const methods_count: u16 = try this.checked_read_u16();
        var methods = try Methods.initCapacity(this.allocator, methods_count);
        errdefer methods.deinit();
        for (0..methods_count) |_| {
            methods.appendAssumeCapacity(try this.read_method_info(&constant_pool));
        }

        const attributes_count = try this.checked_read_u16();
        var attributes = try Attributes.initCapacity(this.allocator, attributes_count);
        errdefer attributes.deinit();
        for (0..attributes_count) |_| {
            attributes.appendAssumeCapacity(try this.read_attribute_info(&constant_pool));
        }

        return .{
            .minor_version = minor_version,
            .major_version = major_version,
            .constant_pool = constant_pool,
            .access_flags = access_flags,
            .this_class = this_class,
            .super_class = super_class,
            .interfaces = interfaces,
            .fields = fields,
            .methods = methods,
            .attributes = attributes,
        };
    }

    fn read_constant_info(this: *Reader) !ConstantInfo {
        if (!this.have_u8()) return error.UnExpectedEOF;
        const tag = try ConstantInfo.Tag.from_u8(this.read_u8());
        if (!this.have_u16()) return error.UnExpectedEOF;
        return switch (tag) {
            .class => .{ .class = .{ .name_index = this.read_u16() } },
            .fieldref => .{ .fieldref = .{
                .class_index = this.read_u16(),
                .name_and_type_index = try this.checked_read_u16(),
            } },
            .methodref => .{ .methodref = .{
                .class_index = this.read_u16(),
                .name_and_type_index = try this.checked_read_u16(),
            } },
            .interface_methodref => .{ .interface_methodref = .{
                .class_index = this.read_u16(),
                .name_and_type_index = try this.checked_read_u16(),
            } },
            .string => .{ .string = .{
                .string_index = this.read_u16(),
            } },
            .integer => .{ .integer = .{
                .bytes = try this.checked_read_u32(),
            } },
            .float => .{ .float = .{
                .bytes = try this.checked_read_u32(),
            } },
            .long => .{ .long = .{
                .high_bytes = try this.checked_read_u32(),
            } },
            .double => .{
                .double = .{
                    .high_bytes = try this.checked_read_u32(),
                },
            },
            .name_and_type => .{ .name_and_type = .{
                .name_index = this.read_u16(),
                .descriptor_index = try this.checked_read_u16(),
            } },
            .utf8 => blk: {
                const length = this.read_u16();
                const bytes = try this.allocator.alloc(u8, length);
                errdefer this.allocator.free(bytes);
                try this.fill_buff(bytes);
                break :blk .{ .utf8 = .{
                    .bytes = bytes,
                } };
            },
            .method_handle => .{ .method_handle = .{
                .refrence_kind = try ConstantInfo.MethodRefKind.from_u8(this.read_u8()),
                .refrence_index = try this.checked_read_u16(),
            } },
            .method_type => .{ .method_type = .{
                .descriptor_index = this.read_u16(),
            } },
            .dynamic => .{ .dynamic = .{
                .bootstrap_method_attr_index = this.read_u16(),
                .name_and_type_index = try this.checked_read_u16(),
            } },
            .invoke_dynamic => .{ .invoke_dynamic = .{
                .bootstrap_method_attr_index = this.read_u16(),
                .name_and_type_index = try this.checked_read_u16(),
            } },
            .module => .{ .module = .{
                .name_index = this.read_u16(),
            } },
            .package => .{ .package = .{
                .name_index = this.read_u16(),
            } },
        };
    }

    fn read_field_info(this: *Reader, constant_pool: *const ConstantPool) !FieldInfo {
        try this.expect_n_bytes(@sizeOf(u16) * 4);
        const access_flags: FieldAccessFlags = @bitCast(this.read_u16());
        const name_index = this.read_u16();
        const descriptor_index = this.read_u16();
        const attributes_count: u16 = this.read_u16();
        var attributes = try Attributes.initCapacity(this.allocator, attributes_count);
        errdefer attributes.deinit();
        for (0..attributes_count) |_| {
            attributes.appendAssumeCapacity(try this.read_attribute_info(constant_pool));
        }

        return .{
            .access_flags = access_flags,
            .name_index = name_index,
            .descriptor_index = descriptor_index,
            .attributes = attributes,
        };
    }

    pub fn read_attribute_info(this: *Reader, constant_pool: *const ConstantPool) !AttributeInfo {
        try this.expect_n_bytes(@sizeOf(u16) + @sizeOf(u32));
        const name_index: u16 = this.read_u16();
        const length = this.read_u32();
        const attr_name = try constant_pool.at_checked(name_index);
        if (attr_name != .utf8) return error.AttributeNameMustBeUTF8;

        var attribute: AttributeInfo.Attribute = undefined;
        const name = attr_name.utf8.bytes;
        if (mem.eql(u8, name, "ConstantValue")) {
            attribute = .{ .ConstantValue = .{
                .constantvalue_index = try this.checked_read_u16(),
            } };
        } else if (mem.eql(u8, name, "Code")) {
            // IMPORTANT(anas): do not forget to free this!
            var code = try this.allocator.create(AttributeInfo.CodeAttribute);
            errdefer this.allocator.destroy(code);
            try this.expect_n_bytes(@sizeOf(u16) * 2 + @sizeOf(u32));
            code.max_stack = this.read_u16();
            code.max_locals = this.read_u16();

            const code_length: u32 = this.read_u32();
            const code_bytes = try this.allocator.alloc(u8, code_length);
            errdefer this.allocator.free(code_bytes);
            try this.fill_buff(code_bytes);
            code.code = std.ArrayList(u8).fromOwnedSlice(this.allocator, code_bytes);

            const exception_table_length: u16 = try this.checked_read_u16();
            var exception_table = try std.ArrayList(AttributeInfo.CodeAttribute.ExceptionTableEntry).initCapacity(this.allocator, exception_table_length);
            errdefer exception_table.deinit();
            for (0..exception_table_length) |_| {
                exception_table.appendAssumeCapacity(try this.read_struct(AttributeInfo.CodeAttribute.ExceptionTableEntry));
            }
            code.exception_table = exception_table;

            const attributes_count: u16 = try this.checked_read_u16();
            var attributes = try Attributes.initCapacity(this.allocator, attributes_count);
            errdefer attributes.deinit();
            for (0..attributes_count) |_| {
                // NOTE(anas): Should we use a separate method for the code attributes?
                // See: Table 4.7-C. https://docs.oracle.com/javase/specs/jvms/se24/html/jvms-4.html#jvms-4.7-320
                attributes.appendAssumeCapacity(try this.read_attribute_info(constant_pool));
            }
            code.attributes = attributes;

            attribute = .{ .Code = code };
        } else if (mem.eql(u8, name, "StackMapTable")) {
            const number_of_entries: u16 = try this.checked_read_u16();
            var entries = try std.ArrayList(AttributeInfo.StackMapFrame).initCapacity(this.allocator, number_of_entries);
            errdefer entries.deinit();
            for (0..number_of_entries) |_| {
                const frame_type: u8 = try this.checked_read_u8();
                switch (frame_type) {
                    0...63 => entries.appendAssumeCapacity(.{ .same_frame = .{ .frame_type = frame_type } }),
                    64...127 => entries.appendAssumeCapacity(.{ .same_locals_1_stack_item_frame = .{
                        .frame_type = frame_type,
                        .stack = .{try this.read_verification_type_info()},
                    } }),
                    247 => entries.appendAssumeCapacity(.{ .same_locals_1_stack_item_frame_extended = .{
                        .offset_delta = try this.checked_read_u16(),
                        .stack = .{try this.read_verification_type_info()},
                    } }),
                    248...250 => entries.appendAssumeCapacity(.{
                        .chop_frame = .{ .frame_type = frame_type, .offset_delta = try this.checked_read_u16() },
                    }),
                    251 => entries.appendAssumeCapacity(.{
                        .same_frame_extended = .{ .offset_delta = try this.checked_read_u16() },
                    }),
                    252...254 => entries.appendAssumeCapacity(.{ .append_frame = .{
                        .frame_type = frame_type,
                        .offset_delta = try this.checked_read_u16(),
                        .locals = blk: {
                            var locals = try this.allocator.alloc(VerificationTypeInfo, frame_type - 251);
                            errdefer this.allocator.free(locals);
                            for (0..(frame_type - 251)) |i| {
                                locals[i] = try this.read_verification_type_info();
                            }
                            break :blk locals;
                        },
                    } }),
                    255 => entries.appendAssumeCapacity(.{ .full_frame = .{ .offset_delta = try this.checked_read_u16(), .locals = blk: {
                        const number_of_locals: u16 = try this.checked_read_u16();
                        var locals = try std.ArrayList(VerificationTypeInfo).initCapacity(this.allocator, number_of_locals);
                        errdefer locals.deinit();
                        for (0..number_of_locals) |_| {
                            locals.appendAssumeCapacity(try this.read_verification_type_info());
                        }
                        break :blk locals;
                    }, .stack = blk: {
                        const number_of_stack_items: u16 = try this.checked_read_u16();
                        var stack = try std.ArrayList(VerificationTypeInfo).initCapacity(this.allocator, number_of_stack_items);
                        errdefer stack.deinit();
                        for (0..number_of_stack_items) |_| {
                            stack.appendAssumeCapacity(try this.read_verification_type_info());
                        }
                        break :blk stack;
                    } } }),
                    else => {
                        // TODO(anas): return error?
                        std.log.err("Unkown stack map frame tag", .{});
                    },
                }
            }
            attribute = .{ .StackMapTable = .{ .entries = entries } };
        } else if (mem.eql(u8, name, "Exceptions")) {
            const number_of_exceptions: u16 = try this.checked_read_u16();
            // TEST(anas): we are not sure if this way is more optimal than the pre allocated ArrayList way
            var entries = try this.allocator.alloc(u16, number_of_exceptions);
            errdefer this.allocator.free(entries);
            try this.expect_n_bytes(@sizeOf(u16) * number_of_exceptions);
            for (0..number_of_exceptions) |i| {
                entries[i] = this.read_u16();
            }
            attribute = .{ .Exceptions = .{ .exception_index_table = std.ArrayList(u16).fromOwnedSlice(this.allocator, entries) } };
        } else if (mem.eql(u8, name, "InnerClasses")) {
            const number_of_classes: u16 = try this.checked_read_u16();
            var classes = try this.allocator.alloc(AttributeInfo.InnerClass, number_of_classes);
            errdefer this.allocator.free(classes);
            for (0..number_of_classes) |i| {
                classes[i] = try this.read_struct(AttributeInfo.InnerClass);
            }
            attribute = .{ .InnerClasses = .{ .classes = std.ArrayList(AttributeInfo.InnerClass).fromOwnedSlice(this.allocator, classes) } };
        } else if (mem.eql(u8, name, "EnclosingMethod")) {
            try this.expect_n_bytes(@sizeOf(u16) * 2);
            attribute = .{ .EnclosingMethod = .{
                .class_index = this.read_u16(),
                .method_index = this.read_u16(),
            } };
        } else if (mem.eql(u8, name, "Synthetic")) {
            if (length != 0) return error.InvalidAttributeLength;
            attribute = .{ .Synthetic = {} };
        } else if (mem.eql(u8, name, "Signature")) {
            attribute = .{ .Signature = .{ .signature_index = try this.checked_read_u16() } };
        } else if (mem.eql(u8, name, "SourceFile")) {
            attribute = .{ .SourceFile = .{ .sourcefile_index = try this.checked_read_u16() } };
        } else if (mem.eql(u8, name, "SourceDebugExtension")) {
            const debug_extension = try this.allocator.alloc(u8, length);
            errdefer this.allocator.free(debug_extension);
            try this.fill_buff(debug_extension);
            attribute = .{ .SourceDebugExtension = .{ .debug_extension = debug_extension } };
        } else if (mem.eql(u8, name, "LineNumberTable")) {
            const tlen: u16 = try this.checked_read_u16();
            std.debug.assert(tlen * @sizeOf(AttributeInfo.LineNumberEntry) == (length - 2));
            var table = try this.allocator.alloc(AttributeInfo.LineNumberEntry, tlen);
            errdefer this.allocator.free(table);
            for (0..tlen) |i| {
                table[i] = try this.read_struct(AttributeInfo.LineNumberEntry);
            }
            attribute = .{ .LineNumberTable = .{
                .line_number_table = std.ArrayList(AttributeInfo.LineNumberEntry).fromOwnedSlice(this.allocator, table),
            } };
        } else if (mem.eql(u8, name, "LocalVariableTable")) {
            const tlen: u16 = try this.checked_read_u16();
            std.debug.assert(tlen * @sizeOf(AttributeInfo.LocalVariableEntry) == (length - 2));
            var table = try this.allocator.alloc(AttributeInfo.LocalVariableEntry, tlen);
            errdefer this.allocator.free(table);
            try this.expect_n_bytes(@sizeOf(AttributeInfo.LocalVariableEntry) * tlen);
            for (0..tlen) |i| {
                table[i] = .{
                    .start_pc = this.read_u16(),
                    .length = this.read_u16(),
                    .name_index = this.read_u16(),
                    .descriptor_index = this.read_u16(),
                    .index = this.read_u16(),
                };
            }
            attribute = .{ .LocalVariableTable = .{
                .local_variable_table = std.ArrayList(AttributeInfo.LocalVariableEntry).fromOwnedSlice(this.allocator, table),
            } };
        } else if (mem.eql(u8, name, "Deprecated")) {
            if (length > 0) return error.InvalidAttributeLength;
            attribute = .{ .Deprecated = {} };
        } else if (mem.eql(u8, name, "RuntimeVisibleAnnotations")) {
            attribute = .{ .RuntimeVisibleAnnotations = try this.read_annotations_collection() };
        } else if (mem.eql(u8, name, "RuntimeInvisibleAnnotations")) {
            attribute = .{ .RuntimeInvisibleAnnotations = try this.read_annotations_collection() };
        } else if (mem.eql(u8, name, "RuntimeVisibleParameterAnnotations")) {
            attribute = .{
                .RuntimeVisibleParameterAnnotations = try this.read_parameter_annotations(),
            };
        } else if (mem.eql(u8, name, "RuntimeInvisibleParameterAnnotations")) {
            attribute = .{ .RuntimeInvisibleParameterAnnotations = try this.read_parameter_annotations() };
        } else if (mem.eql(u8, name, "RuntimeVisibleTypeAnnotations")) {
            attribute = .{ .RuntimeVisibleTypeAnnotations = try this.read_type_annotations_collection() };
        } else {
            std.log.warn("Unkown attribute: {s}", .{name});
            // IMPORTANT(anas): do not forget to free this!
            const bytes = try this.allocator.alloc(u8, length);
            errdefer this.allocator.free(bytes);
            try this.fill_buff(bytes);
            attribute = .{ .Unkown = std.ArrayList(u8).fromOwnedSlice(this.allocator, bytes) };
        }

        return .{
            .name_index = name_index,
            .info = attribute,
        };
    }

    pub fn read_verification_type_info(this: *Reader) !VerificationTypeInfo {
        const tag = try VerificationTypeInfo.Tag.from_u8(try this.checked_read_u8());
        return switch (tag) {
            .Top_variable_info => .{ .Top_variable_info = {} },
            .Integer_variable_info => .{ .Integer_variable_info = {} },
            .Float_variable_info => .{ .Float_variable_info = {} },
            .Long_variable_info => .{ .Long_variable_info = {} },
            .Double_variable_info => .{ .Double_variable_info = {} },
            .Null_variable_info => .{ .Null_variable_info = {} },
            .UninitializedThis_variable_info => .{ .UninitializedThis_variable_info = {} },
            .Object_variable_info => .{ .Object_variable_info = .{
                .cpool_index = try this.checked_read_u16(),
            } },
            .Uninitialized_variable_info => .{ .Uninitialized_variable_info = .{
                .offset = try this.checked_read_u16(),
            } },
        };
    }

    inline fn read_annotations_collection(this: *Reader) !AttributeInfo.AnnotationsCollction {
        const tlen: u16 = try this.checked_read_u16();
        var table = try this.allocator.alloc(AttributeInfo.Annotation, tlen);
        errdefer this.allocator.free(table);
        for (0..tlen) |i| {
            table[i] = try this.read_annotation();
        }
        return .{ .annotations = table };
    }

    fn read_annotation(this: *Reader) anyerror!AttributeInfo.Annotation {
        try this.expect_n_bytes(@sizeOf(u16) * 2);
        const type_index: u16 = this.read_u16();
        const num_element_value_pairs: u16 = this.read_u16();
        var element_value_pairs = try this.allocator.alloc(AttributeInfo.ElementValuePair, num_element_value_pairs);
        errdefer this.allocator.free(element_value_pairs);
        for (0..num_element_value_pairs) |i| {
            element_value_pairs[i] = try this.read_element_value_pair();
        }
        return .{ .type_index = type_index, .element_value_pairs = element_value_pairs };
    }

    inline fn read_element_value_pair(this: *Reader) anyerror!AttributeInfo.ElementValuePair {
        return .{
            .element_name_index = try this.checked_read_u16(),
            .value = try this.read_element_value(),
        };
    }

    fn read_element_value(this: *Reader) anyerror!AttributeInfo.ElementValuePair.ElementValue {
        const ElementValue = AttributeInfo.ElementValuePair.ElementValue;
        const tag = try ElementValue.Tag.from_u8(try this.checked_read_u8());
        const value: ElementValue.Value = switch (tag) {
            .Byte, .Char, .Double, .Float, .Int, .Long, .Short, .Boolean, .String => .{ .const_value_index = try this.checked_read_u16() },
            .Enum => .{ .enum_const_value = blk: {
                try this.expect_n_bytes(@sizeOf(u16) * 2);
                break :blk .{
                    .type_name_index = this.read_u16(),
                    .const_name_index = this.read_u16(),
                };
            } },
            .Class => .{ .class_info_index = try this.checked_read_u16() },
            .Annotation => .{ .annotation = try this.read_annotation() },
            .Array => blk: {
                const num_values: u16 = try this.checked_read_u16();
                var values = try this.allocator.alloc(ElementValue, num_values);
                errdefer this.allocator.free(values);
                for (0..num_values) |i| {
                    values[i] = try this.read_element_value();
                }
                break :blk .{ .array_value = .{ .values = values } };
            },
        };
        return .{ .tag = tag, .value = value };
    }

    inline fn read_parameter_annotations(this: *Reader) !AttributeInfo.ParameterAnnotations {
        const num_parameters: u8 = try this.checked_read_u8();
        var ptaple = try this.allocator.alloc(AttributeInfo.AnnotationsCollction, num_parameters);
        errdefer this.allocator.free(ptaple);
        for (0..num_parameters) |i| {
            ptaple[i] = try this.read_annotations_collection();
        }
        return .{ .parameter_annotations = ptaple };
    }

    inline fn read_type_annotations_collection(this: *Reader) !AttributeInfo.TypeAnnotationsCollction {
        const tlen: u16 = try this.checked_read_u16();
        // std.debug.assert(tlen * @sizeOf(Annotation) == (length - 2));
        var table = try this.allocator.alloc(AttributeInfo.TypeAnnotation, tlen);
        errdefer this.allocator.free(table);
        for (0..tlen) |i| {
            table[i] = try this.read_type_annotation();
        }
        return .{ .annotations = table };
    }

    fn read_type_annotation(this: *Reader) !AttributeInfo.TypeAnnotation {
        var type_ann: AttributeInfo.TypeAnnotation = undefined;
        const target_tag: u8 = try this.checked_read_u8();
        type_ann.target_tag = target_tag;
        type_ann.target_info = switch (target_tag) {
            0x00, 0x01 => .{ .type_parameter_target = .{ .type_parameter_index = try this.checked_read_u8() } },
            0x10 => .{ .supertype_target = .{ .supertype_index = try this.checked_read_u16() } },
            0x11, 0x12 => .{ .type_parameter_bound_target = blk: {
                try this.expect_n_bytes(2);
                break :blk .{
                    .type_parameter_index = this.read_u8(),
                    .bound_index = this.read_u8(),
                };
            } },
            0x13, 0x14, 0x15 => .{ .empty_target = {} },
            0x16 => .{ .formal_parameter_target = .{ .formal_parameter_index = try this.checked_read_u8() } },
            0x17 => .{ .throws_target = .{ .throws_type_index = try this.checked_read_u16() } },
            0x40, 0x41 => .{
                .localvar_target = blk: {
                    const tlen: u16 = try this.checked_read_u16();
                    var table = try this.allocator.alloc(AttributeInfo.TypeAnnotation.LocalVarTableEntry, tlen);
                    errdefer this.allocator.free(table);
                    try this.expect_n_bytes(@sizeOf(AttributeInfo.TypeAnnotation.LocalVarTableEntry) * tlen);
                    for (0..tlen) |i| {
                        // TODO(anas): here `read_struct` do a duplicated length check
                        table[i] = try this.read_struct(AttributeInfo.TypeAnnotation.LocalVarTableEntry);
                    }
                    break :blk .{ .table = table };
                },
            },
            0x42 => .{ .catch_target = .{ .exception_table_index = try this.checked_read_u16() } },
            0x43...0x46 => .{ .offset_target = .{ .offset = try this.checked_read_u16() } },
            0x47...0x4B => .{
                .type_argument_target = blk: {
                    // why i am so alone?
                    try this.expect_n_bytes(@sizeOf(u16) + 1);
                    break :blk .{
                        .offset = this.read_u16(),
                        .type_argument_index = this.read_u8(),
                    };
                },
            },
            else => return error.InvalidTargetTag,
        };
        type_ann.target_path = try this.read_target_path();
        try this.expect_n_bytes(@sizeOf(u16) * 2);
        type_ann.type_index = this.read_u16();
        const num_element_value_pairs: u16 = this.read_u16();
        var element_value_pairs = try this.allocator.alloc(AttributeInfo.ElementValuePair, num_element_value_pairs);
        errdefer this.allocator.free(element_value_pairs);
        for (0..num_element_value_pairs) |i| {
            element_value_pairs[i] = try this.read_element_value_pair();
        }
        type_ann.element_value_pairs = element_value_pairs;
        return type_ann;
    }

    inline fn read_target_path(this: *Reader) !AttributeInfo.TargetPath {
        const len: u8 = try this.checked_read_u8();
        var path = try this.allocator.alloc(AttributeInfo.TargetPath.PathEntry, len);
        errdefer this.allocator.free(path);
        try this.expect_n_bytes(@sizeOf(AttributeInfo.TargetPath.PathEntry) * len);
        for (0..len) |i| {
            path[i] = .{
                .type_path_kind = this.read_u8(),
                .type_argument_index = this.read_u8(),
            };
        }
        return .{ .path = path };
    }

    fn read_method_info(this: *Reader, constant_pool: *const ConstantPool) !MethodInfo {
        try this.expect_n_bytes(@sizeOf(u16) * 4);
        const access_flags: MethodAccessFlags = @bitCast(this.read_u16());
        const name_index: u16 = this.read_u16();
        const descriptor_index: u16 = this.read_u16();
        const attributes_count: u16 = this.read_u16();
        var attributes = try Attributes.initCapacity(this.allocator, attributes_count);
        errdefer attributes.deinit();
        for (0..attributes_count) |_| {
            attributes.appendAssumeCapacity(try this.read_attribute_info(constant_pool));
        }

        return .{ .access_flags = access_flags, .name_index = name_index, .descriptor_index = descriptor_index, .attributes = attributes };
    }
};

pub fn deinit(me: ClassFile) void {
    _ = me;
    // TODO(anas): de-allocate all stuff
}

// https://docs.oracle.com/javase/specs/jvms/se22/html/jvms-4.html#jvms-4.1-200-E.1
pub const ClassAccessFlags = packed struct(u16) {
    public: bool = false,
    _reserved1: u3 = 0,
    final: bool = false,
    super: bool = true,
    _reserved2: u3 = 0,
    interface: bool = false,
    abstract: bool = false,
    _reserved3: u1 = 0,
    synthetic: bool = false,
    annotation: bool = false,
    @"enum": bool = false,
    module: bool = false,

    test "test flag set" {
        const expect = std.testing.expect;
        var caf: ClassAccessFlags = @bitCast(ACC_PUBLIC | ACC_SUPER);
        try expect(caf.public);
        try expect(caf.super);
        try expect(caf.final == false);

        caf = @bitCast(ACC_PUBLIC | ACC_ENUM);
        try expect(caf.public and caf.@"enum");
        try expect(caf.final == false);
        try expect(!(caf.module and caf.annotation and caf.synthetic and caf.super));

        caf = @bitCast(ACC_MODULE | ACC_ABSTRACT | ACC_FINAL);
        try expect(caf.module and caf.abstract);
        try expect(caf.final);
        try expect(!(caf.annotation and caf.synthetic and caf.super));
    }
};

pub const ConstantPool = struct {
    pool: std.ArrayList(ConstantInfo),

    pub inline fn initCapacity(allocator: anytype, size: usize) !ConstantPool {
        return .{ .pool = try std.ArrayList(ConstantInfo).initCapacity(allocator, size) };
    }

    pub inline fn appendAssumeCapacity(me: *ConstantPool, item: ConstantInfo) void {
        me.pool.appendAssumeCapacity(item);
    }

    pub inline fn items(me: *const ConstantPool) []ConstantInfo {
        return me.pool.items;
    }

    pub inline fn at(me: *const ConstantPool, idx: u16) ConstantInfo {
        // if (idx == 0 or idx - 1 > me.pool.items.len) return error.ConstantIndexOutsideRange;
        return me.pool.items[idx - 1];
    }
    pub inline fn at_checked(me: *const ConstantPool, idx: u16) !ConstantInfo {
        if (idx == 0 or idx - 1 > me.pool.items.len) return error.ConstantIndexOutsideRange;
        return me.pool.items[idx - 1];
    }

    pub inline fn deinit(me: @This()) void {
        me.pool.deinit();
    }
};

/// Constant pool table entry. (§4.4)
pub const ConstantInfo = union(ConstantInfo.Tag) {
    // tag: ConstantTag,
    // info: []const u8,
    class: struct {
        name_index: u16,

        pub inline fn resolve_idx(me: @This(), constant_pool: *const ConstantPool) []const u8 {
            // if (idx == 0 or idx - 1 > me.pool.items.len) return error.ConstantIndexOutsideRange;
            return constant_pool.at(me.name_index).utf8.bytes;
        }
    },
    fieldref: RefInfo,
    methodref: RefInfo,
    interface_methodref: RefInfo,
    string: struct {
        string_index: u16,
    },
    integer: Number4Bytes,
    float: Number4Bytes,
    long: Number8Bytes,
    double: Number8Bytes,
    name_and_type: NameAndType,
    utf8: struct {
        // length: u16,
        bytes: []const u8,

        pub fn len(me: @This()) u16 {
            return @as(u16, me.bytes.len);
        }
    },
    method_handle: struct {
        refrence_kind: MethodRefKind,
        refrence_index: u16,
    },
    method_type: struct {
        descriptor_index: u16,
    },
    dynamic: DynamicInfoConst,
    invoke_dynamic: DynamicInfoConst,
    module: struct {
        name_index: u16,
    },
    package: struct {
        name_index: u16,
    },

    pub const Tag = enum(u8) {
        class = 7, // §4.4.1
        fieldref = 9, // §4.4.2
        methodref = 10, // §4.4.2
        interface_methodref = 11, // §4.4.2
        string = 8, //§4.4.3
        integer = 3, //§4.4.4
        float = 4, //§4.4.4
        long = 5, //§4.4.5
        double = 6, //§4.4.5
        name_and_type = 12, // §4.4.6
        utf8 = 1, //§4.4.7
        method_handle = 15, // §4.4.8
        method_type = 16, // §4.4.9
        dynamic = 17, // §4.4.10
        invoke_dynamic = 18, // §4.4.10
        module = 19, // §4.4.11
        package = 20, // §4.4.12

        fn from_u8(v: u8) !Tag {
            inline for (@typeInfo(@This()).@"enum".fields) |f| {
                if (f.value == v) return @field(@This(), f.name);
            }
            return error.InvalidConstantTag;
        }
    };

    /// Bytecode Behaviors for Method Handles (Table 5.4.3.5-A)
    pub const MethodRefKind = enum(u8) {
        REF_getField = 1, // getfield C.f:T
        REF_getStatic = 2, // getstatic C.f:T
        REF_putField = 3, // putfield C.f:T
        REF_putStatic = 4, // putstatic C.f:T
        REF_invokeVirtual = 5, // invokevirtual C.m:(A*)T
        REF_invokeStatic = 6, // invokestatic C.m:(A*)T
        REF_invokeSpecial = 7, // invokespecial C.m:(A*)T
        REF_newInvokeSpecial = 8, // new C; dup; invokespecial C.<init>:(A*)V
        REF_invokeInterface = 9, // invokeinterface C.m:(A*)T

        inline fn from_u8(v: u8) !MethodRefKind {
            if (v == 0 or v > 9) return error.InvalidMethodRefKind;
            return @enumFromInt(v);
        }
    };

    pub const RefInfo = struct {
        class_index: u16,
        name_and_type_index: u16,

        pub fn resolve_class_idx(me: @This(), constant_pool: *const ConstantPool) []const u8 {
            return constant_pool.at(me.class_index).class.resolve_idx(constant_pool);
        }

        pub inline fn resolve_name_and_typ_idx(me: @This(), constant_pool: *const ConstantPool) NameAndType {
            return constant_pool.at(me.name_and_type_index).name_and_type;
        }
    };

    pub const NameAndType = struct {
        name_index: u16,
        descriptor_index: u16,

        pub inline fn resolve_name_idx(me: @This(), constant_pool: *const ConstantPool) []const u8 {
            return constant_pool.at(me.name_index).utf8.bytes;
        }

        pub inline fn resolve_descriptor_idx(me: @This(), constant_pool: *const ConstantPool) []const u8 {
            return constant_pool.at(me.descriptor_index).utf8.bytes;
        }
    };

    pub const Number4Bytes = struct {
        bytes: u32,
    };

    pub const Number8Bytes = union {
        high_bytes: u32,
        low_bytes: u32,
    };

    pub const DynamicInfoConst = struct {
        bootstrap_method_attr_index: u16,
        name_and_type_index: u16,
    };
};

pub const FieldInfo = struct {
    access_flags: FieldAccessFlags,
    name_index: u16,
    descriptor_index: u16,
    // attributes_count: u16,
    attributes: Attributes,
};

pub const FieldAccessFlags = packed struct(u16) {
    public: bool = false,
    private: bool = false,
    protected: bool = false,
    static: bool = false,
    final: bool = false,
    _reserved1: u1 = 0, // 0x0020
    @"volatile": bool = false,
    transient: bool = false,
    _reserved2: u5 = 0,
    synthetic: bool = false,
    @"enum": bool = false,
    _reserved3: u1 = 0,

    test "test bitCast" {
        const expect = std.testing.expect;
        const expect_eq = std.testing.expectEqual;

        var faf: FieldAccessFlags = @bitCast(ACC_PUBLIC | ACC_FINAL);
        try expect(faf.public and faf.final);
        try expect(!(faf.private and faf.protected and faf.static and faf.transient));

        faf = @bitCast(ACC_PROTECTED | ACC_ENUM | ACC_STATIC);
        try expect(faf.protected and faf.@"enum" and faf.static);
        try expect(!(faf.private and faf.public and faf.synthetic and faf.transient));
        try expect_eq(0, faf._reserved1 + faf._reserved2 + faf._reserved3);
    }
};

pub const MethodInfo = struct {
    access_flags: MethodAccessFlags,
    name_index: u16,
    descriptor_index: u16,
    // attributes_count: u16,
    attributes: Attributes,
};

pub const MethodAccessFlags = packed struct(u16) {
    public: bool = false,
    private: bool = false,
    protected: bool = false,
    static: bool = false,
    final: bool = false,
    synchronized: bool = false,
    bridge: bool = false,
    varargs: bool = false,
    native: bool = false,
    _reserved1: u1 = 0,
    abstract: bool = false, // 0x0400
    strict: bool = false, // NOTE(anas): 0x080 is defined only in major version number is at least 46 and at most 60, otherwise its undefined.
    synthetic: bool = false,
    _reserved2: u3 = 0,

    test "test bitCast" {
        const expect = std.testing.expect;
        const expect_eq = std.testing.expectEqual;

        var maf: MethodAccessFlags = @bitCast(ACC_PUBLIC | ACC_FINAL);
        try expect(maf.public and maf.final);
        try expect(!(maf.private and maf.protected and maf.static and maf.strict));

        maf = @bitCast(ACC_PROTECTED | ACC_VARARGS | ACC_STATIC);
        try expect(maf.protected and maf.varargs and maf.static);
        try expect(!(maf.private and maf.public and maf.synthetic and maf.native));
        try expect_eq(0, maf._reserved1 + maf._reserved2);
    }
};

pub const AttributeInfo = struct {
    name_index: u16,
    // length: u32,
    info: Attribute,

    pub const Attribute = union(enum) {
        // NOTE(anas): The value of the attribute_length item must be two.
        ConstantValue: struct {
            /// The value of the constantvalue_index item must be a valid index into the constant_pool table. The constant_pool entry at that index gives the value represented by this attribute.
            constantvalue_index: u16,
        },
        // IMPORTANT(anas):  If the method is either native or abstract, and is not a class or interface initialization method, then its method_info structure must not have a Code attribute in its attributes table. Otherwise, its method_info structure must have exactly one Code attribute in its attributes table.
        Code: *CodeAttribute,
        StackMapTable: struct {
            // number_of_entries: u16,
            entries: std.ArrayList(StackMapFrame),
        },
        Exceptions: struct {
            // number_of_exceptions: u16,
            exception_index_table: std.ArrayList(u16),
        },
        InnerClasses: struct {
            // number_of_classes: u16,
            classes: std.ArrayList(InnerClass),
        },
        EnclosingMethod: struct {
            class_index: u16,
            method_index: u16,
        },
        Synthetic: void, // NOTE(anas): the length must be zero.
        Signature: struct {
            signature_index: u16,
        },
        SourceFile: struct {
            sourcefile_index: u16,
        },
        SourceDebugExtension: struct {
            // The debug_extension array holds extended debugging information which has no semantic effect on the Java Virtual Machine. The information is represented using a modified UTF-8 string (§4.4.7) with no terminating zero byte.
            debug_extension: []const u8,
        },
        LineNumberTable: struct {
            // u2 line_number_table_length;
            line_number_table: std.ArrayList(LineNumberEntry),
        },
        // 4.7.13
        LocalVariableTable: struct {
            // u2 local_variable_table_length;
            local_variable_table: std.ArrayList(LocalVariableEntry),
        },
        Deprecated: void, // NOTE(anas): the length must be zero.
        // NOTE(anas): There may be at most one RuntimeVisibleAnnotations attribute in the attributes table of a ClassFile, field_info, method_info, or record_component_info structure.
        RuntimeVisibleAnnotations: AnnotationsCollction,
        // The RuntimeInvisibleAnnotations attribute is similar to the RuntimeVisibleAnnotations attribute (§4.7.16), except that the annotations represented by a RuntimeInvisibleAnnotations attribute must not be made available for return by reflective APIs, unless the Java Virtual Machine has been instructed to retain these annotations via some implementation-specific mechanism such as a command line flag. In the absence of such instructions, the Java Virtual Machine ignores this attribute.
        RuntimeInvisibleAnnotations: AnnotationsCollction,
        RuntimeVisibleParameterAnnotations: ParameterAnnotations,
        RuntimeInvisibleParameterAnnotations: ParameterAnnotations,
        RuntimeVisibleTypeAnnotations: TypeAnnotationsCollction,
        // TODO(anas): add the rest

        // NOTE(anas): Compilers are permitted to define and emit class files containing new attributes in the attributes tables of class file structures, field_info structures, method_info structures, and Code attributes (§4.7.3).
        // Java Virtual Machine implementations are permitted to recognize and use new attributes found in these attributes tables. However, any attribute not defined as part of this specification must not affect the semantics of the class file. Java Virtual Machine implementations are required to silently ignore attributes they do not recognize.
        Unkown: std.ArrayList(u8),
    };

    pub const CodeAttribute = struct {
        max_stack: u16,
        max_locals: u16,
        // code_length: u32,
        // IMPORTANT(anas):  The value of code_length must be greater than zero (as the code array must not be empty) and less than 65536.
        code: std.ArrayList(u8),
        // exception_table_length: u16,
        exception_table: std.ArrayList(ExceptionTableEntry),
        // attributes_count: u16,
        attributes: Attributes,

        pub const ExceptionTableEntry = packed struct {
            start_pc: u16,
            end_pc: u16,
            handler_pc: u16,
            catch_type: u16,
        };
    };

    pub const StackMapFrame = union(enum) {
        same_frame: struct {
            frame_type: u8, // 0..63
        },
        same_locals_1_stack_item_frame: struct {
            frame_type: u8, // 64..127
            stack: [1]VerificationTypeInfo,
        },
        // NOTE(anas): Tags in the range [128-246] are reserved for future use.
        same_locals_1_stack_item_frame_extended: struct {
            // u1 frame_type = SAME_LOCALS_1_STACK_ITEM_EXTENDED; /* 247 */
            offset_delta: u16,
            stack: [1]VerificationTypeInfo,
        },
        chop_frame: struct {
            frame_type: u8, // = CHOP; /* 248-250 */
            offset_delta: u16,
        },
        same_frame_extended: struct {
            // frame_type: u8, // SAME_FRAME_EXTENDED; /* 251 */
            offset_delta: u16,
        },
        append_frame: struct {
            frame_type: u8, // APPEND; /* 252-254 */
            offset_delta: u16,
            // verification_type_info locals[frame_type - 251];
            locals: []VerificationTypeInfo,
        },
        full_frame: struct {
            // frame_type: u8, // FULL_FRAME; /* 255 */
            offset_delta: u16,
            // number_of_locals: u16,
            locals: std.ArrayList(VerificationTypeInfo),
            // number_of_stack_items: u16,
            stack: std.ArrayList(VerificationTypeInfo),
        },
    };

    pub const InnerClass = packed struct {
        inner_class_info_index: u16,
        outer_class_info_index: u16,
        inner_name_index: u16,
        inner_class_access_flags: u16,
    };

    pub const LineNumberEntry = packed struct {
        start_pc: u16,
        line_number: u16,
    };

    // NOTE(anas): we can't pack this struct because its size aren't even
    pub const LocalVariableEntry = struct {
        start_pc: u16,
        length: u16,
        name_index: u16,
        descriptor_index: u16,
        index: u16,
    };

    // The RuntimeVisibleAnnotations attribute is a variable-length attribute in the attributes table of a ClassFile, field_info, method_info, or record_component_info structure (§4.1, §4.5, §4.6, §4.7.30).
    // The RuntimeVisibleAnnotations attribute stores run-time visible annotations on the declaration of the corresponding class, field, method, or record component.
    pub const AnnotationsCollction = struct {
        // u2         num_annotations;
        // NOTE(anas): I don't think that the user will play alot with the annotations, so no need to pay the ArrayList cost
        // we should also reconsider our decision in using ArrayList in other parts, because i don't think we'll modify the Class object directly anyway
        annotations: []Annotation,
    };

    pub const ParameterAnnotations = struct {
        // u1 num_parameters;
        parameter_annotations: []AnnotationsCollction,
    };

    pub const Annotation = struct {
        // The value of the type_index item must be a valid index into the constant_pool table. The constant_pool entry at that index must be a CONSTANT_Utf8_info structure (§4.4.7) representing a field descriptor (§4.3.2). The field descriptor denotes the type of the annotation represented by this annotation structure.
        type_index: u16,
        // num_element_value_pairs: u16,
        element_value_pairs: []ElementValuePair,
    };

    pub const TypeAnnotationsCollction = struct {
        // u2              num_annotations;
        annotations: []TypeAnnotation,
    };

    pub const TypeAnnotation = struct {
        target_tag: u8,
        target_info: union {
            type_parameter_target: struct { type_parameter_index: u8 },
            supertype_target: struct { supertype_index: u16 },
            type_parameter_bound_target: struct {
                type_parameter_index: u8,
                bound_index: u8,
            },
            //  The empty_target item indicates that an annotation appears on either the type in a field declaration, the type in a record component declaration, the return type of a method, the type of a newly constructed object, or the receiver type of a method or constructor.
            empty_target: void,
            formal_parameter_target: struct { formal_parameter_index: u8 },
            throws_target: struct { throws_type_index: u16 },
            localvar_target: struct {
                // u2 table_length;
                table: []LocalVarTableEntry,
            },
            catch_target: struct { exception_table_index: u16 },
            offset_target: struct { offset: u16 },
            type_argument_target: struct {
                offset: u16,
                type_argument_index: u8,
            },
        },
        target_path: TargetPath,
        type_index: u16,
        // u2        num_element_value_pairs;
        element_value_pairs: []ElementValuePair,

        pub const LocalVarTableEntry = packed struct {
            start_pc: u16,
            length: u16,
            // NOTE(anas): The given local variable must be at index in the local variable array of the current frame.
            // If the local variable at index is of type double or long, it occupies both index and index + 1.
            index: u16,
        };
    };

    //  §4.7.20.2.
    pub const TargetPath = struct {
        // u1 path_length;
        path: []PathEntry,

        pub const PathEntry = packed struct {
            type_path_kind: u8,
            type_argument_index: u8,
        };
    };

    pub const ElementValuePair = struct {
        element_name_index: u16,
        value: ElementValue,

        pub const ElementValue = struct {
            tag: Tag,
            value: Value,

            pub const Tag = enum(u8) {
                Byte = 'B',
                Char = 'C',
                Double = 'D',
                Float = 'F',
                Int = 'I',
                Long = 'J',
                Short = 'S',
                Boolean = 'Z',
                String = 's',
                Enum = 'e',
                Class = 'c',
                Annotation = '@',
                Array = '[',

                fn from_u8(v: u8) !Tag {
                    inline for (@typeInfo(@This()).@"enum".fields) |f| {
                        if (f.value == v) return @field(@This(), f.name);
                    }
                    return error.InvalidElementValueTag;
                }
            };

            pub const Value = union {
                const_value_index: u16,

                enum_const_value: struct {
                    type_name_index: u16,
                    const_name_index: u16,
                },

                class_info_index: u16,

                // TODO(anas): re-check this
                annotation: Annotation,

                array_value: struct {
                    // num_values: u16,
                    values: []ElementValue,
                },
            };
        };
    };
};

pub const VerificationTypeInfo = union(VerificationTypeInfo.Tag) {
    Top_variable_info: void,
    Integer_variable_info: void,
    Float_variable_info: void,
    Long_variable_info: void,
    Double_variable_info: void,
    Null_variable_info: void,
    UninitializedThis_variable_info: void,
    Object_variable_info: struct {
        cpool_index: u16,
    },
    Uninitialized_variable_info: struct {
        offset: u16,
    },

    pub const Tag = enum(u8) {
        Top_variable_info = 0,
        Integer_variable_info = 1,
        Float_variable_info = 2,
        Long_variable_info = 4,
        Double_variable_info = 3,
        Null_variable_info = 5,
        UninitializedThis_variable_info = 6,
        Object_variable_info = 7,
        Uninitialized_variable_info = 8,

        pub inline fn from_u8(v: u8) !@This() {
            if (v < 9) {
                return @enumFromInt(v);
            }
            return error.InvalidVerificationInfoTag;
        }
    };
};
