//! The class file

const std = @import("std");
const mem = std.mem;

// magic: u32,
minor_version: u16,
major_version: u16,
// constant_pool_count: u16,
constant_pool: ConstantPool,
access_flags: ClassAccessFlags,
this_class: u16,
super_class: u16,
// interfaces_count: u16,
interfaces: Interfaces,
// fields_count: u16,
fields: Fields,
// methods_count: u16,
methods: Methods,
// attributes_count: u16,
attributes: Attributes,

const Me = @This();

// NOTE(anas): if we store them as slices it will be more efficient (probably), but we'll need to do alot of add, remove operations
pub const Interfaces = std.ArrayList(u16);
pub const Fields = std.ArrayList(FieldInfo);
pub const Methods = std.ArrayList(MethodInfo);
pub const Attributes = std.ArrayList(AttributeInfo);

pub const MAGIC: u32 = 0xCAFEBABE;

// Access flags.
pub const ACC_PUBLIC: u16 = 0x0001; // Declared public; may be accessed from outside its package.
pub const ACC_PRIVATE: u16 = 0x0002; // Declared private; accessible only within the defining class and other classes belonging to the same nest (§5.4.4).
pub const ACC_PROTECTED: u16 = 0x0004; // Declared protected; may be accessed within subclasses.
pub const ACC_STATIC: u16 = 0x0008; // Declared static.
pub const ACC_FINAL: u16 = 0x0010; // Declared final; no subclasses allowed.
pub const ACC_SUPER: u16 = 0x0020; // Treat superclass methods specially when invoked by the invokespecial instruction.
pub const ACC_SYNCHRONIZED: u16 = 0x0020; // Declared synchronized; invocation is wrapped by a monitor use.
pub const ACC_VOLATILE: u16 = 0x0040; // Declared volatile; cannot be cached.
pub const ACC_BRIDGE: u16 = 0x0040; // A bridge method, generated by the compiler.
pub const ACC_TRANSIENT: u16 = 0x0080; // Declared transient; not written or read by a persistent object manager.
pub const ACC_VARARGS: u16 = 0x0080; // Declared with variable number of arguments.
pub const ACC_NATIVE: u16 = 0x0100; // Declared native; implemented in a language other than the Java programming language.
pub const ACC_INTERFACE: u16 = 0x0200; // Is an interface, not a class.
pub const ACC_ABSTRACT: u16 = 0x0400; // Declared abstract; must not be instantiated.
pub const ACC_STRICT: u16 = 0x0800; // In a class file whose major version number is at least 46 and at most 60: Declared strictfp.
pub const ACC_SYNTHETIC: u16 = 0x1000; // Declared synthetic; not present in the source code.
pub const ACC_ANNOTATION: u16 = 0x2000; // Declared as an annotation interface.
pub const ACC_ENUM: u16 = 0x4000; // Declared as an enum class.
pub const ACC_MODULE: u16 = 0x8000; // Is a module, not a class or interface.

pub fn read(reader: anytype, allocator: std.mem.Allocator) !Me {
    // NOTE(anas): all multi-byte values are encoded as big-endian.
    const magic = try reader.readInt(u32, .big);
    if (magic != MAGIC) {
        return error.InvalidClassFile;
    }
    const minor_version = try reader.readInt(u16, .big);
    const major_version = try reader.readInt(u16, .big);

    const constant_pool_count: u16 = try reader.readInt(u16, .big);
    var constant_pool = try ConstantPool.initCapacity(allocator, constant_pool_count);
    for (0..constant_pool_count - 1) |_| {
        constant_pool.appendAssumeCapacity(try ConstantInfo.read(reader, allocator));
    }

    const access_flags: ClassAccessFlags = @bitCast(try reader.readInt(u16, .big));
    const this_class = try reader.readInt(u16, .big);
    const super_class = try reader.readInt(u16, .big);

    const interfaces_count: u16 = try reader.readInt(u16, .big);
    var interfaces = try Interfaces.initCapacity(allocator, interfaces_count);
    for (0..interfaces_count) |_| {
        interfaces.appendAssumeCapacity(try reader.readInt(u16, .big));
    }

    const fields_count: u16 = try reader.readInt(u16, .big);
    var fields = try Fields.initCapacity(allocator, fields_count);
    for (0..fields_count) |_| {
        fields.appendAssumeCapacity(try FieldInfo.read(reader, allocator, &constant_pool));
    }

    const methods_count: u16 = try reader.readInt(u16, .big);
    var methods = try Methods.initCapacity(allocator, methods_count);
    for (0..methods_count) |_| {
        methods.appendAssumeCapacity(try MethodInfo.read(reader, allocator, &constant_pool));
    }

    const attributes_count = try reader.readInt(u16, .big);
    var attributes = try Attributes.initCapacity(allocator, attributes_count);
    for (0..attributes_count) |_| {
        attributes.appendAssumeCapacity(try AttributeInfo.read(reader, allocator, &constant_pool));
    }

    return .{
        .minor_version = minor_version,
        .major_version = major_version,
        .constant_pool = constant_pool,
        .access_flags = access_flags,
        .this_class = this_class,
        .super_class = super_class,
        .interfaces = interfaces,
        .fields = fields,
        .methods = methods,
        .attributes = attributes,
    };
}

// https://docs.oracle.com/javase/specs/jvms/se22/html/jvms-4.html#jvms-4.1-200-E.1
pub const ClassAccessFlags = packed struct(u16) {
    public: bool = false,
    _reserved1: u3 = 0,
    final: bool = false,
    super: bool = true,
    _reserved2: u3 = 0,
    interface: bool = false,
    abstract: bool = false,
    _reserved3: u1 = 0,
    synthetic: bool = false,
    annotation: bool = false,
    @"enum": bool = false,
    module: bool = false,

    test "test flag set" {
        const expect = std.testing.expect;
        var caf: ClassAccessFlags = @bitCast(ACC_PUBLIC | ACC_SUPER);
        try expect(caf.public);
        try expect(caf.super);
        try expect(caf.final == false);

        caf = @bitCast(ACC_PUBLIC | ACC_ENUM);
        try expect(caf.public and caf.@"enum");
        try expect(caf.final == false);
        try expect(!(caf.module and caf.annotation and caf.synthetic and caf.super));

        caf = @bitCast(ACC_MODULE | ACC_ABSTRACT | ACC_FINAL);
        try expect(caf.module and caf.abstract);
        try expect(caf.final);
        try expect(!(caf.annotation and caf.synthetic and caf.super));
    }
};

pub const ConstantPool = struct {
    pool: std.ArrayList(ConstantInfo),

    pub inline fn initCapacity(allocator: anytype, size: usize) !ConstantPool {
        return .{ .pool = try std.ArrayList(ConstantInfo).initCapacity(allocator, size) };
    }

    pub inline fn appendAssumeCapacity(me: *ConstantPool, item: ConstantInfo) void {
        me.pool.appendAssumeCapacity(item);
    }

    pub inline fn items(me: *const ConstantPool) []ConstantInfo {
        return me.pool.items;
    }

    pub inline fn at(me: *const ConstantPool, idx: u16) ConstantInfo {
        // if (idx == 0 or idx - 1 > me.pool.items.len) return error.ConstantIndexOutsideRange;
        return me.pool.items[idx - 1];
    }
    pub inline fn at_checked(me: *const ConstantPool, idx: u16) !ConstantInfo {
        if (idx == 0 or idx - 1 > me.pool.items.len) return error.ConstantIndexOutsideRange;
        return me.pool.items[idx - 1];
    }
};

/// Constant pool table entry. (§4.4)
pub const ConstantInfo = union(ConstantInfo.Tag) {
    // tag: ConstantTag,
    // info: []const u8,
    class: struct {
        name_index: u16,

        pub inline fn resolve_idx(me: @This(), constant_pool: *const ConstantPool) []const u8 {
            // if (idx == 0 or idx - 1 > me.pool.items.len) return error.ConstantIndexOutsideRange;
            return constant_pool.at(me.name_index).utf8.bytes;
        }
    },
    fieldref: RefInfo,
    methodref: RefInfo,
    interface_methodref: RefInfo,
    string: struct {
        string_index: u16,
    },
    integer: Number4Bytes,
    float: Number4Bytes,
    long: Number8Bytes,
    double: Number8Bytes,
    name_and_type: NameAndType,
    utf8: struct {
        // length: u16,
        bytes: []const u8,

        pub fn len(me: @This()) u16 {
            return @as(u16, me.bytes.len);
        }
    },
    method_handle: struct {
        refrence_kind: MethodRefKind,
        refrence_index: u16,
    },
    method_type: struct {
        descriptor_index: u16,
    },
    dynamic: DynamicInfoConst,
    invoke_dynamic: DynamicInfoConst,
    module: struct {
        name_index: u16,
    },
    package: struct {
        name_index: u16,
    },

    pub const Tag = enum(u8) {
        class = 7, // §4.4.1
        fieldref = 9, // §4.4.2
        methodref = 10, // §4.4.2
        interface_methodref = 11, // §4.4.2
        string = 8, //§4.4.3
        integer = 3, //§4.4.4
        float = 4, //§4.4.4
        long = 5, //§4.4.5
        double = 6, //§4.4.5
        name_and_type = 12, // §4.4.6
        utf8 = 1, //§4.4.7
        method_handle = 15, // §4.4.8
        method_type = 16, // §4.4.9
        dynamic = 17, // §4.4.10
        invoke_dynamic = 18, // §4.4.10
        module = 19, // §4.4.11
        package = 20, // §4.4.12

        fn from_u8(v: u8) !Tag {
            inline for (@typeInfo(@This()).@"enum".fields) |f| {
                if (f.value == v) return @field(@This(), f.name);
            }
            return error.InvalidConstantTag;
        }
    };

    /// Bytecode Behaviors for Method Handles (Table 5.4.3.5-A)
    pub const MethodRefKind = enum(u8) {
        REF_getField = 1, // getfield C.f:T
        REF_getStatic = 2, // getstatic C.f:T
        REF_putField = 3, // putfield C.f:T
        REF_putStatic = 4, // putstatic C.f:T
        REF_invokeVirtual = 5, // invokevirtual C.m:(A*)T
        REF_invokeStatic = 6, // invokestatic C.m:(A*)T
        REF_invokeSpecial = 7, // invokespecial C.m:(A*)T
        REF_newInvokeSpecial = 8, // new C; dup; invokespecial C.<init>:(A*)V
        REF_invokeInterface = 9, // invokeinterface C.m:(A*)T

        inline fn from_u8(v: u8) !MethodRefKind {
            if (v == 0 or v > 9) return error.InvalidMethodRefKind;
            return @enumFromInt(v);
        }
    };

    pub const RefInfo = struct {
        class_index: u16,
        name_and_type_index: u16,

        pub fn resolve_class_idx(me: @This(), constant_pool: *const ConstantPool) []const u8 {
            return constant_pool.at(me.class_index).class.resolve_idx(constant_pool);
        }

        pub inline fn resolve_name_and_typ_idx(me: @This(), constant_pool: *const ConstantPool) NameAndType {
            return constant_pool.at(me.name_and_type_index).name_and_type;
        }
    };

    pub const NameAndType = struct {
        name_index: u16,
        descriptor_index: u16,

        pub inline fn resolve_name_idx(me: @This(), constant_pool: *const ConstantPool) []const u8 {
            return constant_pool.at(me.name_index).utf8.bytes;
        }

        pub inline fn resolve_descriptor_idx(me: @This(), constant_pool: *const ConstantPool) []const u8 {
            return constant_pool.at(me.descriptor_index).utf8.bytes;
        }
    };

    pub const Number4Bytes = struct {
        bytes: u32,
    };

    pub const Number8Bytes = struct {
        high_bytes: u32,
        low_bytes: u32,

        pub fn as_long(me: Number8Bytes) u64 {
            return (@as(u64, me.high_bytes) << 32) | me.low_bytes;
        }

        pub fn as_double(me: Number8Bytes) f64 {
            // Combine the high and low bytes into a single u64
            const bits: u64 = (@as(u64, me.high_bytes) << 32) | me.low_bytes;

            // Extract sign bit
            const s: i32 = if ((bits >> 63) == 0) 1 else -1;

            // Extract exponent
            const e: i32 = @intCast((bits >> 52) & 0x7FF);

            // Extract mantissa
            const m: u64 = if (e == 0)
                (bits & 0xFFFFFFFFFFFFF) << 1
            else
                (bits & 0xFFFFFFFFFFFFF) | 0x10000000000000;

            // Handle special cases
            if (e == 0x7FF) {
                // Infinity or NaN
                if (m == 0) {
                    return if (s == 1) std.math.inf(f64) else -std.math.inf(f64);
                } else {
                    return std.math.nan(f64);
                }
            }

            // Calculate the value
            const exponent = e - 1023;
            const mantissa_value = @as(f64, @floatFromInt(m)) / @as(f64, @floatFromInt(0x10000000000000));
            const result = @as(f64, @floatFromInt(s)) * mantissa_value * std.math.pow(f64, 2.0, @floatFromInt(exponent));

            return result;
        }
    };

    pub const DynamicInfoConst = struct {
        bootstrap_method_attr_index: u16,
        name_and_type_index: u16,
    };

    pub fn read(reader: anytype, allocator: std.mem.Allocator) !ConstantInfo {
        const tag = try Tag.from_u8(try reader.readByte());
        return switch (tag) {
            .class => .{ .class = .{ .name_index = try reader.readInt(u16, .big) } },
            .fieldref => .{ .fieldref = .{
                .class_index = try reader.readInt(u16, .big),
                .name_and_type_index = try reader.readInt(u16, .big),
            } },
            .methodref => .{ .methodref = .{
                .class_index = try reader.readInt(u16, .big),
                .name_and_type_index = try reader.readInt(u16, .big),
            } },
            .interface_methodref => .{ .interface_methodref = .{
                .class_index = try reader.readInt(u16, .big),
                .name_and_type_index = try reader.readInt(u16, .big),
            } },
            .string => .{ .string = .{
                .string_index = try reader.readInt(u16, .big),
            } },
            .integer => .{ .integer = .{
                .bytes = try reader.readInt(u16, .big),
            } },
            .float => .{ .float = .{
                .bytes = try reader.readInt(u16, .big),
            } },
            .long => .{ .long = .{
                .high_bytes = try reader.readInt(u32, .big),
                .low_bytes = try reader.readInt(u32, .big),
            } },
            .double => .{ .double = .{
                .high_bytes = try reader.readInt(u32, .big),
                .low_bytes = try reader.readInt(u32, .big),
            } },
            .name_and_type => .{ .name_and_type = .{
                .name_index = try reader.readInt(u16, .big),
                .descriptor_index = try reader.readInt(u16, .big),
            } },
            .utf8 => blk: {
                const length = try reader.readInt(u16, .big);
                const bytes = try allocator.alloc(u8, length);
                // TEST(anas): make sure that this function returns an error when there is no enough bytes
                _ = try reader.readAtLeast(bytes, length);
                break :blk .{ .utf8 = .{
                    .bytes = bytes,
                } };
            },
            .method_handle => .{ .method_handle = .{
                .refrence_kind = try MethodRefKind.from_u8(try reader.readByte()),
                .refrence_index = try reader.readInt(u16, .big),
            } },
            .method_type => .{ .method_type = .{
                .descriptor_index = try reader.readInt(u16, .big),
            } },
            .dynamic => .{ .dynamic = .{
                .bootstrap_method_attr_index = try reader.readInt(u16, .big),
                .name_and_type_index = try reader.readInt(u16, .big),
            } },
            .invoke_dynamic => .{ .invoke_dynamic = .{
                .bootstrap_method_attr_index = try reader.readInt(u16, .big),
                .name_and_type_index = try reader.readInt(u16, .big),
            } },
            .module => .{ .module = .{
                .name_index = try reader.readInt(u16, .big),
            } },
            .package => .{ .package = .{
                .name_index = try reader.readInt(u16, .big),
            } },
        };
    }
};

pub const FieldInfo = struct {
    access_flags: FieldAccessFlags,
    name_index: u16,
    descriptor_index: u16,
    // attributes_count: u16,
    attributes: Attributes,

    fn read(reader: anytype, allocator: mem.Allocator, constant_pool: *const ConstantPool) !FieldInfo {
        const access_flags: FieldAccessFlags = @bitCast(try reader.readInt(u16, .big));
        const name_index = try reader.readInt(u16, .big);
        const descriptor_index = try reader.readInt(u16, .big);

        const attributes_count: u16 = try reader.readInt(u16, .big);
        var attributes = try Attributes.initCapacity(allocator, attributes_count);
        for (0..attributes_count) |_| {
            attributes.appendAssumeCapacity(try AttributeInfo.read(reader, allocator, constant_pool));
        }

        return .{
            .access_flags = access_flags,
            .name_index = name_index,
            .descriptor_index = descriptor_index,
            .attributes = attributes,
        };
    }
};

pub const FieldAccessFlags = packed struct(u16) {
    public: bool = false,
    private: bool = false,
    protected: bool = false,
    static: bool = false,
    final: bool = false,
    _reserved1: u1 = 0, // 0x0020
    @"volatile": bool = false,
    transient: bool = false,
    _reserved2: u5 = 0,
    synthetic: bool = false,
    @"enum": bool = false,
    _reserved3: u1 = 0,

    test "test bitCast" {
        const expect = std.testing.expect;
        const expect_eq = std.testing.expectEqual;

        var faf: FieldAccessFlags = @bitCast(ACC_PUBLIC | ACC_FINAL);
        try expect(faf.public and faf.final);
        try expect(!(faf.private and faf.protected and faf.static and faf.transient));

        faf = @bitCast(ACC_PROTECTED | ACC_ENUM | ACC_STATIC);
        try expect(faf.protected and faf.@"enum" and faf.static);
        try expect(!(faf.private and faf.public and faf.synthetic and faf.transient));
        try expect_eq(0, faf._reserved1 + faf._reserved2 + faf._reserved3);
    }
};

pub const MethodInfo = struct {
    access_flags: MethodAccessFlags,
    name_index: u16,
    descriptor_index: u16,
    // attributes_count: u16,
    attributes: Attributes,

    pub fn read(reader: anytype, allocator: mem.Allocator, constant_pool: *const ConstantPool) !MethodInfo {
        const access_flags: MethodAccessFlags = @bitCast(try reader.readInt(u16, .big));
        const name_index: u16 = try reader.readInt(u16, .big);
        const descriptor_index: u16 = try reader.readInt(u16, .big);

        const attributes_count: u16 = try reader.readInt(u16, .big);
        var attributes = try Attributes.initCapacity(allocator, attributes_count);
        for (0..attributes_count) |_| {
            attributes.appendAssumeCapacity(try AttributeInfo.read(reader, allocator, constant_pool));
        }

        return .{ .access_flags = access_flags, .name_index = name_index, .descriptor_index = descriptor_index, .attributes = attributes };
    }
};

pub const MethodAccessFlags = packed struct(u16) {
    public: bool = false,
    private: bool = false,
    protected: bool = false,
    static: bool = false,
    final: bool = false,
    synchronized: bool = false,
    bridge: bool = false,
    varargs: bool = false,
    native: bool = false,
    _reserved1: u1 = 0,
    abstract: bool = false, // 0x0400
    strict: bool = false, // NOTE(anas): 0x080 is defined only in major version number is at least 46 and at most 60, otherwise its undefined.
    synthetic: bool = false,
    _reserved2: u3 = 0,

    test "test bitCast" {
        const expect = std.testing.expect;
        const expect_eq = std.testing.expectEqual;

        var maf: MethodAccessFlags = @bitCast(ACC_PUBLIC | ACC_FINAL);
        try expect(maf.public and maf.final);
        try expect(!(maf.private and maf.protected and maf.static and maf.strict));

        maf = @bitCast(ACC_PROTECTED | ACC_VARARGS | ACC_STATIC);
        try expect(maf.protected and maf.varargs and maf.static);
        try expect(!(maf.private and maf.public and maf.synthetic and maf.native));
        try expect_eq(0, maf._reserved1 + maf._reserved2);
    }
};

pub const AttributeInfo = struct {
    name_index: u16,
    // length: u32,
    info: Attribute,

    pub const Attribute = union(enum) {
        ConstantValue: struct {
            constantvalue_index: u16,
        },
        Code: *CodeAttribute,
        StackMapTable: struct {
            // number_of_entries: u16,
            entries: std.ArrayList(StackMapFrame),
        },
        Exceptions: struct {
            // number_of_exceptions: u16,
            exception_index_table: std.ArrayList(u16),
        },
        InnerClasses: struct {
            // number_of_classes: u16,
            classes: std.ArrayList(struct {
                inner_class_info_index: u16,
                outer_class_info_index: u16,
                inner_name_index: u16,
                inner_class_access_flags: u16,
            }),
        },
        EnclosingMethod: struct {
            class_index: u16,
            method_index: u16,
        },
        Synthetic: void, // NOTE(anas): the length must be zero.
        Signature: struct {
            signature_index: u16,
        },
        SourceFile: struct {
            sourcefile_index: u16,
        },
        SourceDebugExtension: struct {
            // The debug_extension array holds extended debugging information which has no semantic effect on the Java Virtual Machine. The information is represented using a modified UTF-8 string (§4.4.7) with no terminating zero byte.
            debug_extension: []const u8,
        },
        LineNumberTable: struct {
            // u2 line_number_table_length;
            line_number_table: std.ArrayList(struct {
                start_pc: u16,
                line_number: u16,
            }),
        },
        // 4.7.13
        LocalVariableTable: struct {
            // u2 local_variable_table_length;
            local_variable_table: std.ArrayList(struct {
                start_pc: u16,
                length: u16,
                name_index: u16,
                descriptor_index: u16,
                index: u16,
            }),
        },
        // NOTE(anas): Compilers are permitted to define and emit class files containing new attributes in the attributes tables of class file structures, field_info structures, method_info structures, and Code attributes (§4.7.3).
        // Java Virtual Machine implementations are permitted to recognize and use new attributes found in these attributes tables. However, any attribute not defined as part of this specification must not affect the semantics of the class file. Java Virtual Machine implementations are required to silently ignore attributes they do not recognize.
        Unkown: std.ArrayList(u8),
    };

    pub const CodeAttribute = struct {
        max_stack: u16,
        max_locals: u16,
        // code_length: u32,
        // IMPORTANT(anas):  The value of code_length must be greater than zero (as the code array must not be empty) and less than 65536.
        code: std.ArrayList(u8),
        // exception_table_length: u16,
        exception_table: std.ArrayList(ExceptionTableEntry),
        // attributes_count: u16,
        attributes: Attributes,

        pub const ExceptionTableEntry = packed struct {
            start_pc: u16,
            end_pc: u16,
            handler_pc: u16,
            catch_type: u16,
        };
    };

    pub const StackMapFrame = union(enum) {
        same_frame: struct {
            frame_type: u8, // 0..63
        },
        same_locals_1_stack_item_frame: struct {
            frame_type: u8, // 64..127
            stack: [1]VerificationTypeInfo,
        },
        // NOTE(anas): Tags in the range [128-246] are reserved for future use.
        same_locals_1_stack_item_frame_extended: struct {
            // u1 frame_type = SAME_LOCALS_1_STACK_ITEM_EXTENDED; /* 247 */
            offset_delta: u16,
            stack: [1]VerificationTypeInfo,
        },
        chop_frame: struct {
            frame_type: u8, // = CHOP; /* 248-250 */
            offset_delta: u16,
        },
        same_frame_extended: struct {
            frame_type: u8, // SAME_FRAME_EXTENDED; /* 251 */
            offset_delta: u16,
        },
        append_frame: struct {
            frame_type: u8, // APPEND; /* 252-254 */
            offset_delta: u16,
            // verification_type_info locals[frame_type - 251];
            locals: std.ArrayList(VerificationTypeInfo),
        },
        full_frame: struct {
            // frame_type: u8, // FULL_FRAME; /* 255 */
            offset_delta: u16,
            // number_of_locals: u16,
            locals: std.ArrayList(VerificationTypeInfo),
            // number_of_stack_items: u16,
            stack: std.ArrayList(VerificationTypeInfo),
        },
    };

    pub fn read(reader: anytype, allocator: mem.Allocator, constant_pool: *const ConstantPool) !AttributeInfo {
        const name_index: u16 = try reader.readInt(u16, .big);
        const length = try reader.readInt(u32, .big);
        const attr_name = try constant_pool.at_checked(name_index);
        if (attr_name != .utf8) return error.AttributeNameMustBeUTF8;

        var attribute: Attribute = undefined;
        const name = attr_name.utf8.bytes;
        if (mem.eql(u8, name, "ConstantValue")) {
            attribute = .{ .ConstantValue = .{
                .constantvalue_index = try reader.readInt(u16, .big),
            } };
        } else if (mem.eql(u8, name, "Code")) {
            // IMPORTANT(anas): do not forget to free this!
            var code = try allocator.create(CodeAttribute);
            code.max_stack = try reader.readInt(u16, .big);
            code.max_locals = try reader.readInt(u16, .big);

            const code_length: u32 = try reader.readInt(u32, .big);
            const code_bytes = try allocator.alloc(u8, code_length);
            _ = try reader.readAtLeast(code_bytes, code_length);
            code.code = std.ArrayList(u8).fromOwnedSlice(allocator, code_bytes);

            const exception_table_length: u16 = try reader.readInt(u16, .big);
            var exception_table = try std.ArrayList(CodeAttribute.ExceptionTableEntry).initCapacity(allocator, exception_table_length);
            for (0..exception_table_length) |_| {
                exception_table.appendAssumeCapacity(try reader.readStructEndian(CodeAttribute.ExceptionTableEntry, .big));
            }
            code.exception_table = exception_table;

            const attributes_count: u16 = try reader.readInt(u16, .big);
            var attributes = try Attributes.initCapacity(allocator, attributes_count);
            for (0..attributes_count) |_| {
                attributes.appendAssumeCapacity(try AttributeInfo.read(reader, allocator, constant_pool));
            }
            code.attributes = attributes;

            attribute = .{ .Code = code };
        } else {
            std.log.warn("Unkown attribute: {s}", .{name});
            // IMPORTANT(anas): do not forget to free this!
            const bytes = try allocator.alloc(u8, length);
            _ = try reader.readAtLeast(bytes, length);
            attribute = .{ .Unkown = std.ArrayList(u8).fromOwnedSlice(allocator, bytes) };
        }

        return .{
            .name_index = name_index,
            .info = attribute,
        };
    }
};

pub const VerificationTypeInfo = union(enum) {
    // Top_variable_info;
    // Integer_variable_info;
    // Float_variable_info;
    // Long_variable_info;
    // Double_variable_info;
    // Null_variable_info;
    // UninitializedThis_variable_info;
    // Object_variable_info;
    // Uninitialized_variable_info;
};
